export const QUESTION_TEMPLATES: Record<string, any[]> = {
    "Data Structures & Algorithms": [
        { text: "What is the time complexity of binary search?", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], correctAnswer: "O(log n)" },
        { text: "Which data structure uses FIFO?", options: ["Stack", "Queue", "Tree", "Graph"], correctAnswer: "Queue" },
        { text: "Which traversal gives sorted output in BST?", options: ["Preorder", "Postorder", "Inorder", "Level order"], correctAnswer: "Inorder" },
        { text: "Time complexity of quicksort (average)?", options: ["O(n²)", "O(n log n)", "O(log n)", "O(n)"], correctAnswer: "O(n log n)" },
        { text: "Which DS is used for recursion?", options: ["Queue", "Stack", "Heap", "Tree"], correctAnswer: "Stack" },
        { text: "Worst case of quicksort?", options: ["O(n)", "O(log n)", "O(n log n)", "O(n²)"], correctAnswer: "O(n²)" },
        { text: "Hash table average lookup time?", options: ["O(n)", "O(log n)", "O(1)", "O(n log n)"], correctAnswer: "O(1)" },
        { text: "Which is not a linear DS?", options: ["Array", "Stack", "Graph", "Queue"], correctAnswer: "Graph" },
        { text: "Space complexity of merge sort?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: "O(n)" },
        { text: "Detect cycle in graph uses?", options: ["BFS", "DFS", "Both", "None"], correctAnswer: "Both" },
        { text: "Heap is used in?", options: ["DFS", "Dijkstra", "BFS", "Sorting only"], correctAnswer: "Dijkstra" },
        { text: "Best DS for LRU cache?", options: ["Array", "Linked List + HashMap", "Stack", "Tree"], correctAnswer: "Linked List + HashMap" },
        { text: "What is a balanced BST?", options: ["Equal nodes", "Height difference ≤1", "Sorted tree", "Binary tree"], correctAnswer: "Height difference ≤1" },
        { text: "Graph with no cycles?", options: ["DAG", "Tree", "Both", "None"], correctAnswer: "Both" },
        { text: "Which sorting is stable?", options: ["Quick", "Heap", "Merge", "Selection"], correctAnswer: "Merge" },
        { text: "BFS uses?", options: ["Stack", "Queue", "Heap", "Array"], correctAnswer: "Queue" },
        { text: "Stack overflow occurs when?", options: ["Empty", "Full", "Both", "None"], correctAnswer: "Full" },
        { text: "Linked list access time?", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], correctAnswer: "O(n)" },
        { text: "Which DS for undo operation?", options: ["Queue", "Stack", "Heap", "Graph"], correctAnswer: "Stack" },
        { text: "Height of balanced BST?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], correctAnswer: "O(log n)" },
        { text: "Which uses priority queue?", options: ["BFS", "Dijkstra", "DFS", "Merge"], correctAnswer: "Dijkstra" },
        { text: "What is collision in hashing?", options: ["Same key", "Same index", "Same value", "None"], correctAnswer: "Same index" },
        { text: "Which DS for shortest path?", options: ["Stack", "Queue", "Graph", "Tree"], correctAnswer: "Graph" },
        { text: "Which is divide & conquer?", options: ["BFS", "QuickSort", "DFS", "Linear Search"], correctAnswer: "QuickSort" },
        { text: "Time complexity of heap insert?", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], correctAnswer: "O(log n)" }
    ],
    "DBMS": [
        { text: "Primary key is?", options: ["Unique + Not null", "Only unique", "Only not null", "None"], correctAnswer: "Unique + Not null" },
        { text: "SQL stands for?", options: ["Structured Query Language", "Simple Query Language", "System Query Language", "None"], correctAnswer: "Structured Query Language" },
        { text: "Normalization reduces?", options: ["Redundancy", "Speed", "Data", "Queries"], correctAnswer: "Redundancy" },
        { text: "Which is NoSQL?", options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], correctAnswer: "MongoDB" },
        { text: "JOIN combines?", options: ["Rows", "Columns", "Tables", "DBs"], correctAnswer: "Tables" },
        { text: "ACID property A = ?", options: ["Atomicity", "Accuracy", "Access", "Allocation"], correctAnswer: "Atomicity" },
        { text: "Index improves?", options: ["Insert", "Read", "Delete", "None"], correctAnswer: "Read" },
        { text: "Foreign key is?", options: ["Unique", "Reference key", "Primary", "None"], correctAnswer: "Reference key" },
        { text: "Which is DDL?", options: ["SELECT", "INSERT", "CREATE", "UPDATE"], correctAnswer: "CREATE" },
        { text: "Which normal form removes partial dependency?", options: ["1NF", "2NF", "3NF", "BCNF"], correctAnswer: "2NF" }
    ],
    "OS": [
        { text: "OS manages?", options: ["Hardware", "Software", "Both", "None"], correctAnswer: "Both" },
        { text: "Process is?", options: ["Program in execution", "File", "Thread", "None"], correctAnswer: "Program in execution" },
        { text: "Deadlock needs?", options: ["Mutual exclusion", "Hold & wait", "No preemption", "All"], correctAnswer: "All" },
        { text: "Context switch is?", options: ["Process switch", "Memory change", "Disk swap", "None"], correctAnswer: "Process switch" },
        { text: "Virtual memory uses?", options: ["RAM", "Disk", "Cache", "CPU"], correctAnswer: "Disk" },
        { text: "Scheduling algorithm?", options: ["FCFS", "SJF", "Round Robin", "All"], correctAnswer: "All" }
    ],
    "Networking": [
        { text: "HTTP is?", options: ["Stateless", "Stateful", "Both", "None"], correctAnswer: "Stateless" },
        { text: "HTTPS uses?", options: ["SSL/TLS", "FTP", "TCP", "UDP"], correctAnswer: "SSL/TLS" },
        { text: "TCP is?", options: ["Reliable", "Unreliable", "Fast", "None"], correctAnswer: "Reliable" },
        { text: "DNS does?", options: ["IP → Domain", "Domain → IP", "Both", "None"], correctAnswer: "Domain → IP" }
    ],
    "Backend": [
        { text: "REST API is?", options: ["Stateless", "Stateful", "Both", "None"], correctAnswer: "Stateless" },
        { text: "HTTP status 200?", options: ["Error", "Success", "Redirect", "Fail"], correctAnswer: "Success" },
        { text: "Middleware in Node?", options: ["DB", "Function", "API", "Server"], correctAnswer: "Function" },
        { text: "JWT is used for?", options: ["Auth", "DB", "Cache", "Logs"], correctAnswer: "Auth" },
        { text: "Which DB is relational?", options: ["MongoDB", "MySQL", "Redis", "Firebase"], correctAnswer: "MySQL" }
    ],
    "Frontend": [
        { text: "Which is not JS framework?", options: ["React", "Angular", "Vue", "Django"], correctAnswer: "Django" },
        { text: "useState is?", options: ["Hook", "API", "DB", "Class"], correctAnswer: "Hook" },
        { text: "Virtual DOM improves?", options: ["Speed", "UI", "Memory", "None"], correctAnswer: "Speed" },
        { text: "CSS Flexbox is for?", options: ["Layout", "DB", "Logic", "API"], correctAnswer: "Layout" },
        { text: "Closure means?", options: ["Function + scope", "Loop", "Object", "None"], correctAnswer: "Function + scope" },
        { text: "Promise is?", options: ["Sync", "Async", "DB", "None"], correctAnswer: "Async" },
        { text: "== vs === ?", options: ["Same", "Type check", "No diff", "None"], correctAnswer: "Type check" },
        { text: "Event bubbling?", options: ["Child → Parent", "Parent → Child", "Both", "None"], correctAnswer: "Child → Parent" },
        { text: "LocalStorage is?", options: ["Server", "Browser", "DB", "API"], correctAnswer: "Browser" },
        { text: "React key prop?", options: ["Styling", "Unique ID", "State", "None"], correctAnswer: "Unique ID" },
        { text: "DOM stands for?", options: ["Document Object Model", "Data Object Model", "None", "Both"], correctAnswer: "Document Object Model" },
        { text: "CSS position absolute?", options: ["Fixed", "Relative to parent", "Static", "None"], correctAnswer: "Relative to parent" },
        { text: "Async/Await is?", options: ["Sync", "Async", "Loop", "None"], correctAnswer: "Async" },
        { text: "useEffect used for?", options: ["Side effects", "Styling", "Routing", "None"], correctAnswer: "Side effects" },
        { text: "Props are?", options: ["Immutable", "Mutable", "Both", "None"], correctAnswer: "Immutable" },
        { text: "State is?", options: ["Mutable", "Immutable", "Both", "None"], correctAnswer: "Mutable" },
        { text: "JSON stands for?", options: ["JavaScript Object Notation", "Java Syntax Object Notation", "None", "Both"], correctAnswer: "JavaScript Object Notation" },
        { text: "Arrow function uses?", options: ["Lexical this", "Dynamic this", "Both", "None"], correctAnswer: "Lexical this" },
        { text: "NPM is?", options: ["Package manager", "DB", "API", "None"], correctAnswer: "Package manager" },
        { text: "SPA means?", options: ["Single Page App", "Simple Page App", "Server Page App", "None"], correctAnswer: "Single Page App" }
    ]
};
